### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by orpheus92** [cyclus/rickshaw#6]
Does rickshaw only support python 3.4+? 
I am getting the syntax error with python 2.7. 
I built Cyclus and Cycamore 2.7. Will there be a problem with that? 

Thanks

**Comment by FlanFlanagan** [comment]
At the moment it does. This is a requirement of the websockets portion I believe

**Comment by orpheus92** [comment]
Is it possible to use python 2.7 for Cyclus and python3.4+ for rickshaw? Would there be conflicts then?

**Comment by FlanFlanagan** [comment]
Yes, but the server functional in cyclus is python 3.4 as well. This won't cause issues unless you try to use cyclus server functionality

**Comment by scopatz** [comment]
In all likelihood it is v3.5+. If you need help getting a more recent version of Python, I recommend using conda/anaconda/miniconda

**Comment by orpheus92** [comment]
I'll close this since it works for python3.6

**Comment by scopatz** [comment]
Thanks!
